package com.example.demo_springboot_api.modules.example.controller;

import com.example.demo_springboot_api.common.dto.BaseResponse;
import com.example.demo_springboot_api.modules.example.constant.*;
import com.example.demo_springboot_api.modules.example.entity.Project;
import com.example.demo_springboot_api.modules.example.repository.ProjectRepository;
import java.util.Iterator;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;

@Controller
@RequestMapping(ModuleConstants.BASE_PATH + "/dev")
public class TestController {
  @Autowired // This means to get the bean called userRepository
  // Which is auto-generated by Spring, we will use it to handle the data
  private ProjectRepository projectRepository;

  @PostMapping(path = "/add")
  public @ResponseBody String addNewUser(@RequestParam String code, @RequestParam String name) {

    Project n = new Project();
    n.setCode(code);
    n.setName(name);
    projectRepository.save(n);
    return "Saved";
  }

  @GetMapping(path = "/getall")
  public @ResponseBody ResponseEntity<BaseResponse<String, String>> getAllUsers() {
    String out = "";
    Iterator<Project> users = projectRepository.findAll().iterator();
    while (users.hasNext()) {
      Project user = users.next();
      out += user.getName();
      if (users.hasNext()) {
        out += ", ";
      }
    }

    return ResponseEntity.status(HttpStatus.OK)
        .body(BaseResponse.success("Get all successfully", out));
  }
}
