package com.example.demo_springboot_api.modules.example.controller;

import com.example.demo_springboot_api.common.dto.ApiResponse;
import com.example.demo_springboot_api.common.utils.ResponseHelper;
import com.example.demo_springboot_api.config.constants.WebSocketConstants;
import com.example.demo_springboot_api.modules.example.constant.*;
import com.example.demo_springboot_api.modules.example.dto.message.ClientGreeting;
import com.example.demo_springboot_api.modules.example.dto.message.ServerGreeting;
import com.example.demo_springboot_api.modules.example.entity.Project;
import com.example.demo_springboot_api.modules.example.repository.ProjectRepository;
import java.util.Iterator;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.messaging.handler.annotation.DestinationVariable;
import org.springframework.messaging.handler.annotation.MessageMapping;
import org.springframework.messaging.handler.annotation.Payload;
import org.springframework.messaging.simp.SimpMessagingTemplate;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;
import org.springframework.web.util.HtmlUtils;

@Controller
@RequestMapping(ModuleConstants.BASE_PATH + "/dev")
public class TestController {
  @Autowired // This means to get the bean called userRepository
  // Which is auto-generated by Spring, we will use it to handle the data
  private ProjectRepository projectRepository;

  @Autowired private SimpMessagingTemplate messagingTemplate;

  @PostMapping(path = "/add")
  public @ResponseBody String addNewUser(@RequestParam String code, @RequestParam String name) {

    Project n = new Project();
    n.setCode(code);
    n.setName(name);
    projectRepository.save(n);
    return "Saved";
  }

  @GetMapping(path = "/getall")
  public @ResponseBody ResponseEntity<ApiResponse<String>> getAllUsers() {
    String out = "";
    Iterator<Project> users = projectRepository.findAll().iterator();
    while (users.hasNext()) {
      Project user = users.next();
      out += user.getName();
      if (users.hasNext()) {
        out += ", ";
      }
    }

    return ResponseEntity.status(HttpStatus.OK)
        .body(ResponseHelper.success("Get all successfully", out, ApiResponse::new));
  }

  @MessageMapping("/hello/{roomId}")
  public void greeting(@DestinationVariable String roomId, @Payload ClientGreeting message)
      throws Exception {
    Thread.sleep(1000); // simulated delay

    String destination = WebSocketConstants.BROKER_ENDPOINT + "/greetings/room." + roomId;
    messagingTemplate.convertAndSend(
        destination, new ServerGreeting("Hello, " + HtmlUtils.htmlEscape(message.name()) + "!"));
  }
}
