package com.example.demo_springboot_api.modules.user.controller;

import com.example.demo_springboot_api.common.dto.BaseResponse;
import com.example.demo_springboot_api.common.encoder.token.TokenEncoder;
import com.example.demo_springboot_api.modules.user.constant.ModuleConstants;
import com.example.demo_springboot_api.modules.user.entity.User;
import com.example.demo_springboot_api.modules.user.repository.UserRepository;
import com.example.demo_springboot_api.modules.user.service.UserService;
import java.util.Iterator;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.security.crypto.password.PasswordEncoder;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;

@Controller
@RequestMapping(ModuleConstants.BASE_PATH + "/dev")
public class DevController {
  @Autowired // This means to get the bean called userRepository
  // Which is auto-generated by Spring, we will use it to handle the data
  private UserRepository userRepository;

  @Autowired // This means to get the bean called userRepository
  // Which is auto-generated by Spring, we will use it to handle the data
  private UserService userService;

  @Autowired private PasswordEncoder encoder;

  @Autowired private TokenEncoder tokenEncoder;

  @PostMapping(path = "/add")
  public @ResponseBody String addNewUser(
      @RequestParam String code,
      @RequestParam String name,
      @RequestParam String email,
      @RequestParam String password) {

    User n = new User();
    n.setCode(code);
    n.setName(name);
    n.setEmail(email);
    n.setPassword(password);
    userService.addUser(n);
    return "Saved";
  }

  @PostMapping(path = "/getall")
  public @ResponseBody ResponseEntity<BaseResponse<String, String>> getAllUsers() {
    String out = "";
    Iterator<User> users = userRepository.findAll().iterator();
    while (users.hasNext()) {
      User user = users.next();
      out += user.getName();
      if (users.hasNext()) {
        out += ", ";
      }
    }

    return ResponseEntity.status(HttpStatus.OK)
        .body(BaseResponse.success("Get all successfully", out));
  }

  @GetMapping(path = "/test-encode")
  public @ResponseBody ResponseEntity<BaseResponse<String, String>> testPasswordEncode(
      @RequestParam String input) {
    String out = encoder.encode(input);

    return ResponseEntity.status(HttpStatus.OK)
        .body(BaseResponse.success("Test encode successfully", out));
  }

  @GetMapping(path = "/test-hash")
  public @ResponseBody ResponseEntity<BaseResponse<String, String>> testHash(
      @RequestParam String input) {
    String out = tokenEncoder.encode(input);

    return ResponseEntity.status(HttpStatus.OK)
        .body(BaseResponse.success("Test hash successfully", out));
  }
}
