import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Provider } from "@/components/ui/provider"
import { config } from "@/config/config";
import { createGenerateMetadataFunc } from "@/utils/createGenerateMetadataFunc";
import { Toaster } from "@/components/ui/toaster";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

/*
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
*/

export const generateMetadata = createGenerateMetadataFunc({
  title: {
    default: "w4u.io.vn",
    id: "app.title",
  },
})

export default async function RootLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params: Promise<{ locale: typeof config.LOCALES[number] }>;
}>) {
  const { locale } = await params;

  return (
    <html lang={locale} suppressHydrationWarning>
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <Provider intlProviderProps={{ locale }}>
          {children}
          <Toaster />
        </Provider>
      </body>
    </html>
  );
}
