package com.example.demo_springboot_api.modules.auth.controller;

import com.example.demo_springboot_api.modules.auth.constant.ModuleConstants;
import com.example.demo_springboot_api.modules.user.entity.User;
import com.example.demo_springboot_api.modules.user.repository.UserRepository;
import java.util.Optional;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;

@Controller
@RequestMapping(ModuleConstants.BASE_PATH)
public class CodeAuthController {
  @Autowired // This means to get the bean called userRepository
  // Which is auto-generated by Spring, we will use it to handle the data
  private UserRepository userRepository;

  @PostMapping(path = "/login")
  public @ResponseBody String addNewUser(
      @RequestParam String loginKey, @RequestParam String password) {

    Optional<User> userQuery = userRepository.findByEmail(loginKey);

    if (userQuery.isEmpty()) {
    }

    /*
      User n = new User();
      n.setCode(code);
      n.setName(name);
      n.setEmail(email);
      userRepository.save(n);
    */
    return "Saved";
  }

  /*
  @PostMapping(path = "/getall")
  public @ResponseBody ResponseEntity<BaseResponse<String, String>> getAllUsers() {
    String out = "";
    Iterator<User> users = userRepository.findAll().iterator();
    while (users.hasNext()) {
      User user = users.next();
      out += user.getName();
      if (users.hasNext()) {
        out += ", ";
      }
    }

    return ResponseEntity.status(HttpStatus.OK)
        .body(BaseResponse.success("Get all successfully", out));
  }
  */
}
