package com.example.demo_springboot_api.modules.auth.controller;

import com.example.demo_springboot_api.common.errors.UserNotFoundException;
import com.example.demo_springboot_api.modules.auth.constant.ModuleConstants;
import com.example.demo_springboot_api.modules.auth.dto.LoginResponse;
import com.example.demo_springboot_api.modules.auth.service.ConfiguredUserDetails;
import com.example.demo_springboot_api.modules.auth.service.JwtService;
import com.example.demo_springboot_api.modules.user.entity.User;
import com.example.demo_springboot_api.modules.user.repository.UserRepository;
import java.util.Optional;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.security.crypto.password.PasswordEncoder;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;

@Controller
@RequestMapping(ModuleConstants.BASE_PATH)
public class CodeAuthController {
  @Autowired // This means to get the bean called userRepository
  // Which is auto-generated by Spring, we will use it to handle the data
  private UserRepository userRepository;

  @Autowired private PasswordEncoder encoder;

  @Autowired private JwtService jwtService;

  @PostMapping(path = "/login")
  public @ResponseBody ResponseEntity<LoginResponse> addNewUser(
      @RequestParam String loginKey, @RequestParam String password) {

    Optional<User> userQuery = userRepository.findByEmail(loginKey);

    if (userQuery.isEmpty()) {
      throw new UserNotFoundException("User with provided email does not exists.");
    }

    User user = userQuery.get();
    if (encoder.matches(password, user.getPassword())) {
      return ResponseEntity.status(HttpStatus.OK)
          .body(
              LoginResponse.success(
                  "Login successfully", jwtService.generateToken(new ConfiguredUserDetails(user))));
    }

    return ResponseEntity.status(HttpStatus.UNAUTHORIZED)
        .body(LoginResponse.success("Login unsuccessfully", "Wrong email or password"));
  }

  /*
  @PostMapping(path = "/getall")
  public @ResponseBody ResponseEntity<BaseResponse<String, String>> getAllUsers() {
    String out = "";
    Iterator<User> users = userRepository.findAll().iterator();
    while (users.hasNext()) {
      User user = users.next();
      out += user.getName();
      if (users.hasNext()) {
        out += ", ";
      }
    }

    return ResponseEntity.status(HttpStatus.OK)
        .body(BaseResponse.success("Get all successfully", out));
  }
  */
}
